from .theme import make_theme

UNICORN_THEME = make_theme(
    fontname='Comic Sans MS',
    graph_bgcolor='#f8fffa', graph_fontcolor='#7d7d7d',
    label_bgcolor='#eafff5',
    edge_color='#b3b3b3',
    node_fillcolor='#f5eaff', node_fontcolor='#7d7d7d',
    start_fillcolor='#baffc9', start_fontcolor='#7d7d7d',
    end_fillcolor='#bae1ff', end_fontcolor='#7d7d7d',
    error_fillcolor='#ffe0e9', error_fontcolor='#b47a8c', error_edge_color='#e6b3c2',
    warn_fillcolor='#fffacc', warn_fontcolor='#b3a86c', warn_edge_color='#e6e0b3',
    info_fillcolor='#e0fff4', info_fontcolor='#7db8a3', info_edge_color='#b3e6d7',
    service_colors=[
        ("#ffe0e9", "#7d7d7d"),
        ("#fffacc", "#7d7d7d"),
        ("#e0fff4", "#7d7d7d"),
        ("#bae1ff", "#7d7d7d"),
        ("#f5eaff", "#7d7d7d"),
        ("#ffd6e0", "#7d7d7d"),
        ("#e2f0cb", "#7d7d7d"),
        ("#f9e2ae", "#7d7d7d"),
        ("#f7cac9", "#7d7d7d"),
        ("#baffc9", "#7d7d7d"),
        ("#c5d1eb", "#7d7d7d"),
        ("#f6dfeb", "#7d7d7d"),
    ],
    group_colors=[
        ("#f8fffa", "#b3b3b3"),
        ("#eafff5", "#b3b3b3"),
        ("#f5eaff", "#b3b3b3"),
        ("#ffe0e9", "#b3b3b3"),
        ("#fffacc", "#b3b3b3"),
        ("#e0fff4", "#b3b3b3"),
        ("#bae1ff", "#b3b3b3"),
        ("#ffd6e0", "#b3b3b3"),
    ],
)